### PR TITLE
update contact Page(links work, dark mode, content, theme{background with some animations simple design})

### PR DESCRIPTION
**Pull request by Kritika30032002**
issue #89

update contact Page(links work, dark mode, content, theme{background with some animations simple design})

### CODE REVIEW

**Comment by ElvinPero** [comment]
PLease add ss or vids of  work as per pr template

**Comment by ElvinPero** [comment]
@Kritika30032002

**Comment by Kritika30032002** [comment]
> @Kritika30032002

Screenshot (19451)
Screenshot (19452)

**Comment by Kritika30032002** [comment]
@ElvinPero

**Comment by ElvinPero** [comment]
@Kritika30032002 1) It is contact us(not contact me)
2) Please design the form layout in dark with white text during dark mode . 
3) For any queries regarding templates ,contact us (This line can be added )your line has gramatical mistakes.

**Comment by ElvinPero** [comment]
It has been a lot of time since i assigned and this result more or less looks like the previous one  :/
can you make a good contact us ? or are you fine with me assigning someone else

**Comment by Kritika30032002** [comment]
> It has been a lot of time since i assigned and this result more or less looks like the previous one :/ can you make a good contact us ? or are you fine with me assigning someone else

you can assign to someone else!

**Pull request closed without merging**
