### PR TITLE
Created A About Page & Bug Fixes

### PR DESCRIPTION
**Pull request by EXPOLK**
Fixed didn't work button in the index.html file and contact.html file.
Created A About Page

Issue No: #103

### CODE REVIEW

**Comment by ElvinPero** [comment]
@EXPOLK Could you make it such that About in both nav and footer scrolls down to the about in index.html

**Comment by EXPOLK** [comment]
> @EXPOLK Could you make it such that About in both nav and footer scrolls down to the about in index.html

@ElvinPero Did you mean removing the about page and set the nav bar about button to scroll down to the bottom of the index?
If you mean that I will try through a new pull request, So can you merge this please?

**Comment by ElvinPero** [comment]
About us is already there in main page .. what i want is for about and about us button to scroll to that portion of page which has about us .. no need for separate about us .. there is already one in main page

**Comment by EXPOLK** [comment]
Okay I will delete the about us separate page and make it correctly

**Comment by ElvinPero** [comment]
conflicts

**Comment by ElvinPero** [comment]
@EXPOLK issue solved already thanks for work though

**Pull request closed without merging**
