### PR TITLE
issue with about-us button solved

### PR DESCRIPTION
**Pull request by UditDe**
### Brief description
If you click on about Us button it will redirect on the about us section in the same page. So now, there is no requirement of a different aboutUs.html page

### Screenshots or videos (if appropriate)

https://user-images.githubusercontent.com/98590230/195970722-32e73e2c-58fc-43d5-bf95-c87c9c26b898.mp4

# Important points to keep in mind before raising PR

### CODE REVIEW

**Comment by ElvinPero** [comment]
@UditDe Can you do one more thing  ? Match the blue rectangle in about us to the color of site so it changes by change style.

**Comment by UditDe** [comment]
> @UditDe Can you do one more thing ? Match the blue rectangle in about us to the color of site so it changes by change style.

sure

**Comment by ElvinPero** [comment]
@UditDe 
image
also this its whole blue when cursor . text becomes invisible.
All these will enhance the about us so i can merge

**Comment by UditDe** [comment]
I have done those changes that you said....

https://user-images.githubusercontent.com/98590230/195981457-7bc184ab-d507-482b-8974-f0b65f78e07e.mp4

**Pull request merged**
