### PR TITLE
Issue #76 solve, custom scrollbar added

### PR DESCRIPTION
**Pull request by MridulTailor**
Screenshot 2022-10-11 at 9 13 25 PM

### CODE REVIEW

**Comment by ElvinPero** [comment]
@MridulTailor Why isnt it working on the site after merge. Code looks fine though. Could you be solve this.

**Comment by MridulTailor** [comment]
Maybe this...
Screenshot 2022-10-11 at 9 56 48 PM

**Comment by ElvinPero** [comment]
I am on chrome its not working

**Comment by ElvinPero** [comment]
@MridulTailor Its working properly Thanks for your contribution happy coding.

**Comment by MridulTailor** [comment]
Thank you Elvin.

**Pull request merged**
