### PR TITLE
Contact us page added

### PR DESCRIPTION
**Pull request by neeldoshii**

### CODE REVIEW

**Comment by neeldoshii** [comment]
I did the basic code for contact us. Hope you guys improve it. I am still a beginner at the moment.

**Comment by ElvinPero** [comment]
> I did the basic code for contact us. Hope you guys improve it. I am still a beginner at the moment. 

Kindly follow the pr template .. include screenshots or recordings of your work

**Comment by neeldoshii** [comment]
What's the PR template?

**Comment by ElvinPero** [comment]
@neeldoshii see the issues

**Pull request merged**
