### PR TITLE
Solved issue no. #87

### PR DESCRIPTION
**Pull request by Upasana-Roy**
### Screenshots or videos (if appropriate)

# Important points to keep in mind before raising PR

### CODE REVIEW

**Comment by ElvinPero** [comment]
@Upasana-Roy Please follow the PR template

**Comment by Upasana-Roy** [comment]
@ElvinPero I have resolved the Conflicts

**Comment by ElvinPero** [comment]
@Upasana-Roy Upload ss or vid of you work

**Comment by Upasana-Roy** [comment]
Screenshot (87)
@ElvinPero Here is the screenshot of the About Us Section

**Comment by ElvinPero** [comment]
@Upasana-Roy Can you change things a bit so I can merge (wouldn't take much time)
1) Have a bit light theme for about us so in dark mode it can change.
2) Some content in brief about templates 3 lines
3) remove discord for now ..

**Comment by ElvinPero** [comment]
@Upasana-Roy Also upload ss of both light and dark when new commit

**Comment by Upasana-Roy** [comment]
Screenshot (91)

Screenshot (90)
@ElvinPero  Light and Dark mode of About Us Section

**Comment by ElvinPero** [comment]
@Upasana-Roy Your Pr has changed the navbar . please fix it to original nav

**Comment by ElvinPero** [comment]
Also color in dark mode was a bit darker .update that and i will add hacktoberfest-accepted label

**Comment by Upasana-Roy** [comment]
@ElvinPero which portion of the Navbar is changed?? Can you please specify that

**Comment by ElvinPero** [comment]
image
@Upasana-Roy

**Pull request merged**
