### PR TITLE
refactor: update toggle-mode button height

### PR DESCRIPTION
**Pull request by ftonato**
CleanShot 2022-10-10 at 11 21 53

### CODE REVIEW

**Comment by ElvinPero** [comment]
@ftonato there should be a toggle switch and all other description are written in the issue .

**Comment by ElvinPero** [comment]
I can merge this for now but issue needs to be cleared

**Comment by ftonato** [comment]
Thanks @ElvinPero, could you also add the `hacktoberfest-accepted` and `hacktoberfest` labels, if you deem the contribution something valid for such an event?!

**Comment by ftonato** [comment]
Thanks @ElvinPero, could you also add the `hacktoberfest-accepted` and `hacktoberfest` labels, if you deem the contribution something valid for such an event?!

**Pull request merged**
