### PR TITLE
Autogenerated PR template added

### PR DESCRIPTION
**Pull request by suryansh-bhatnagar**
https://user-images.githubusercontent.com/90460257/195436478-18bce094-f360-491d-a4c4-f78590ddac86.mp4

### CODE REVIEW

**Comment by ElvinPero** [comment]
@suryansh-bhatnagar Please follow the pr template that already exists :/

**Comment by suryansh-bhatnagar** [comment]
> @suryansh-bhatnagar Please follow the pr template that already exists :/

It is almost  same as already existing template,  i have made just little needy changes

**Comment by ElvinPero** [comment]
> > @suryansh-bhatnagar Please follow the pr template that already exists :/
> 
> It is almost  same as already existing template,  i have made just little needy changes.
> @ElvinPero  Do you want exactly same??

I am saying in your own pr pless add ss or vids

**Comment by suryansh-bhatnagar** [comment]
> > > @suryansh-bhatnagar Please follow the pr template that already exists :/
> > 
> > 
> > It is almost  same as already existing template,  i have made just little needy changes.
> > @ElvinPero  Do you want exactly same??
> 
> I am saying in your own pr please add ss or vids



> > > @suryansh-bhatnagar Please follow the pr template that already exists :/
> > 
> > 
> > It is almost  same as already existing template,  i have made just little needy changes.
> > @ElvinPero  Do you want exactly same??
> 
> I am saying in your own pr please add ss or vids

Oh , got it

**Comment by suryansh-bhatnagar** [comment]
> > > > @suryansh-bhatnagar Please follow the pr template that already exists :/
> > > 
> > > 
> > > It is almost  same as already existing template,  i have made just little needy changes.
> > > @ElvinPero  Do you want exactly same??
> > 
> > 
> > I am saying in your own pr please add ss or vids
> 
> > > > @suryansh-bhatnagar Please follow the pr template that already exists :/
> > > 
> > > 
> > > It is almost  same as already existing template,  i have made just little needy changes.
> > > @ElvinPero  Do you want exactly same??
> > 
> > 
> > I am saying in your own pr please add ss or vids
> 
> Oh , got it

Done

**Pull request merged**
