### PR TITLE
Preloader/udit

### PR DESCRIPTION
**Pull request by UditDe**
### Brief description
I have added a preloader page for the website

### Screenshots or videos (if appropriate)

# Important points to keep in mind before raising PR
#### Only assignees can PR

https://user-images.githubusercontent.com/98590230/195984847-fa20d9b6-0ea7-4b69-80fc-d8ca40be9148.mp4

### CODE REVIEW

**Comment by ElvinPero** [comment]
@UditDe Could you make a futuristic design preloader with dark background

**Comment by UditDe** [comment]
Sure

**Comment by UditDe** [comment]
is that ok?

https://user-images.githubusercontent.com/98590230/195997850-0cae5b7a-4613-4460-a772-3a3a0db12f98.mp4

**Comment by ElvinPero** [comment]
The preloader is fine but it is making bugs in deploy preview like:
contact page links not working
back to top  button not visible.
You can do one thing .. sync the current fork , clone it then add the preloader

**Comment by UditDe** [comment]
If there is any conflict, then please let me know

**Pull request merged**
