### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Upasana-Roy**
Image issue solved

### Screenshots or videos (if appropriate)

# Important points to keep in mind before raising PR

### CODE REVIEW

**Comment by Upasana-Roy** [comment]
@ElvinPero The image issue is solved. Can you please verify

**Comment by ElvinPero** [comment]
> @ElvinPero The image issue is solved. Can you please verify

Thanks for contributing. Happy coding

**Comment by Upasana-Roy** [comment]
@ElvinPero can you please add hacktoberfest-accepted label here

**Comment by ElvinPero** [comment]
@Upasana-Roy It is added in previous PR . This is too simplistic and bug fix of your previous PR, so may be rejected

**Comment by Upasana-Roy** [comment]
Ok thanks

**Pull request merged**
