### PR TITLE
Toggle Button Is Added

### PR DESCRIPTION
**Pull request by devjain2309**
Toggle button is Added.

### CODE REVIEW

**Comment by devjain2309** [comment]
@ElvinPero please give me a proper description of why you closed my PR without merging.

**Comment by ElvinPero** [comment]
@devjain2309 Unassigned PR

**Comment by devjain2309** [comment]
@ElvinPero Sorry for that, but check out once my PR if you like it then you are free to use it.

**Comment by ElvinPero** [comment]
@devjain2309  I had checked your code before closing PR . But merging is only fair when assigned person gets the chance to contribute else it would be unfair to the assignee. Thanks for your effort, you can still create other issue and commit there. Happy coding

**Pull request closed without merging**
